### ISSUE TITLE
Received status code 401 from server

### ISSUE THREAD

**Issue by mdeveracoding** [foreseecode/foresee-sdk-android-samples#55]
I try to build the localizationsample but get the error below:

Could not GET 'https://maven.pkg.github.com/foreseecode/public-packages/com/foresee/sdk/cxmeasure/6.1.0-github-test-0.1/cxmeasure-6.1.0-github-test-0.1.pom'. Received status code 401 from server: Unauthorized
Disable Gradle 'offline mode' and sync project

What is the correct directory location for configuring  a settings.xml so that I may use a github credential?

**Comment by sleeke** [comment]
Apologies for this oversight - it seems there's been an unwanted commit to the `master` branch. 

We'll make sure a fix is applied as soon as possible, but in the meantime, you should be able to solve the issue by checking out the `release/6.0.3` branch instead. 

Thanks!

**Comment by sleeke** [comment]
This should also now be permanently fixed on the `master` branch
